name: 'StackSpot Run Command'
description: 'GitHub Action to run CLI Command'
branding:
  icon: 'arrow-up-circle'
  color: 'orange'

inputs:
  client_id:
    description: Account client id
    required: true
  client_key:
    description: Account client key
    required: true
  realm:
    description: Account realm
    required: true
  command_stk:
    description: Command STK
    required: false
    default: ''
  working_directory:
    description: Working directory
    required: false
    default: '.'    

runs:
  using: "composite"
  steps:
    - name: Check if STK CLI Installed
      id: check_cli
      shell: bash
      run: |
        if [ -f "$HOME/.stk/bin/stk" ]; then
            echo "STK_INSTALLED=true" >> "$GITHUB_ENV"
        else
            echo "STK_INSTALLED=false" >> "$GITHUB_ENV"
        fi

    - name: Install STK CLI
      if: env.STK_INSTALLED == 'false'
      shell: bash
      run: |
        curl \
          --fail \
          --http2-prior-knowledge \
          --location \
          --silent \
          --show-error \
          --tlsv1.3 \
          https://stk.stackspot.com/install.sh | bash

    - name: Check if STK CLI Installed
      id: check_cli2
      shell: bash
      run: |
        if [ -f "$HOME/.stk/bin/stk" ]; then
            echo "STK_INSTALLED=true" >> "$GITHUB_ENV"
            echo "PATH=$PATH:$HOME/.stk/bin" >> "$GITHUB_ENV"
        else
            echo "STK_INSTALLED=false" >> "$GITHUB_ENV"
        fi

    - name: Show STK CLI version
      shell: bash
      run: stk --version

    - name: Login StackSpot
      shell: bash
      env:
        CLIENT_ID: ${{ inputs.client_id }}
        CLIENT_KEY: ${{ inputs.client_key }}
        REALM: ${{ inputs.realm }}
      run: |
        stk login --client-id $CLIENT_ID --client-key $CLIENT_KEY --realm $REALM

    - name: Run Command
      shell: bash
      run: |
        cd ${{ inputs.working_directory }}
        stk ${{ inputs.command_stk }}

    - name: Show Error Log
      shell: bash    
      if: ${{ failure() }}
      run: |
        [ -d "$HOME/.stk/logs/" ] && [ "$(ls -A $HOME/.stk/logs/)" ] && cat $HOME/.stk/logs/*
        exit 1