name: Action test

on:
  push:
    paths:
      - '.github/workflows/action-test.yml'
      - 'action.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Run test action
        uses: stack-spot/cli-github-action-run-command@add-action
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_key: ${{ secrets.CLIENT_KEY }}
          realm: ${{ secrets.REALM }}
          command_stk: "--version"

      - name: Run test action again
        uses: stack-spot/cli-github-action-run-command@add-action
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_key: ${{ secrets.CLIENT_KEY }}
          realm: ${{ secrets.REALM }}
          command_stk: ""
